# Generated by Django 4.2.1 on 2023-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="delete_flg",
            field=models.BooleanField(default=False),
        ),
    ]
